version: '3'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f
# docker rmi -f avito-segmentator

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - './db/:/docker-entrypoint-initdb.d/'

  usersegmentator:
    build: .
    container_name: avito-user-segmentator-api
    image: avito-segmentator
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mysql

